include_role 'base'

include_cookbook 'xcode'
include_cookbook 'homebrew'
include_cookbook 'git'
include_cookbook 'vim'
include_cookbook 'neovim'
include_cookbook 'zsh'
include_cookbook 'ghq'
include_cookbook 'peco'
include_cookbook 'fzf'
include_cookbook 'ag'
include_cookbook 'thunderbolt'
include_cookbook 'go'
include_cookbook 'tmux'
include_cookbook 'karabiner'
include_cookbook 'source-code-pro'
include_cookbook 'bin'

dotfile '.gemrc'
dotfile '.karabiner'
dotfile '.peco'
dotfile '.pryrc'
dotfile '.psqlrc'
dotfile '.railsrc'
dotfile '.rake'
