include_role 'base'

include_cookbook 'xcode'
include_cookbook 'homebrew'
include_cookbook 'git'
include_cookbook 'vim'
include_cookbook 'zsh'
include_cookbook 'peco'
include_cookbook 'fzf'
include_cookbook 'ag'
include_cookbook 'tmux'
include_cookbook 'gnupg'
include_cookbook 'bin'
include_cookbook 'karabiner'
include_cookbook 'rust'
include_cookbook 'ruby'

dotfile '.peco'
dotfile '.psqlrc'
dotfile '.rake'
dotfile '.tigrc'
dotfile '.globalrc'
dotfile '.rubocop.yml'
dotfile '.iterm2'
dotfile '.ideavimrc'
